/*
 * Julianne Wojdak
 * 29/10/18
 * Course Mark Calculator
 */

/**
 *
 * @author JuWoj8013
 */
public class FormCourseMarkCalculator extends javax.swing.JFrame {

    /**
     * Creates new form FormCourseMarkCalculator
     */
    public FormCourseMarkCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HeadingLabel = new javax.swing.JLabel();
        Mark1Label = new javax.swing.JLabel();
        Mark2Label = new javax.swing.JLabel();
        Mark3Label = new javax.swing.JLabel();
        Mark4Label = new javax.swing.JLabel();
        Mark5Label = new javax.swing.JLabel();
        SubheadingLabel = new javax.swing.JLabel();
        Mark1Text = new javax.swing.JTextField();
        Mark2Text = new javax.swing.JTextField();
        Mark3Text = new javax.swing.JTextField();
        Mark4Text = new javax.swing.JTextField();
        Mark5Text = new javax.swing.JTextField();
        CalculateButton = new javax.swing.JButton();
        AverageLabel = new javax.swing.JLabel();
        AverageLabel2 = new javax.swing.JLabel();
        DisplayLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        HeadingLabel.setFont(new java.awt.Font("AbcPrint", 0, 18)); // NOI18N
        HeadingLabel.setText("Course Mark Calculator");

        Mark1Label.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Mark1Label.setText("Course Mark 1:");

        Mark2Label.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Mark2Label.setText("Course Mark 2:");

        Mark3Label.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Mark3Label.setText("Course Mark 3:");

        Mark4Label.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Mark4Label.setText("Course Mark 4:");

        Mark5Label.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Mark5Label.setText("Course Mark 5:");

        SubheadingLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        SubheadingLabel.setText("Enter 5 marks and click to calculate your average");

        Mark1Text.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N

        Mark2Text.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Mark2Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mark2TextActionPerformed(evt);
            }
        });

        Mark3Text.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N

        Mark4Text.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N

        Mark5Text.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N

        CalculateButton.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        CalculateButton.setText("Calculate");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        AverageLabel.setFont(new java.awt.Font("AbcPrint", 0, 14)); // NOI18N
        AverageLabel.setText("Your Average Is:");

        AverageLabel2.setFont(new java.awt.Font("AbcPrint", 0, 14)); // NOI18N
        AverageLabel2.setText("0.0%");

        DisplayLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mark2Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Mark2Text))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mark1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Mark1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mark3Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Mark3Text))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mark4Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Mark4Text))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mark5Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Mark5Text)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(CalculateButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(AverageLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AverageLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(DisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(HeadingLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(SubheadingLabel)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(HeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubheadingLabel)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AverageLabel)
                                    .addComponent(AverageLabel2))
                                .addGap(55, 55, 55))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Mark1Label)
                                    .addComponent(Mark1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CalculateButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Mark2Label)
                                    .addComponent(Mark2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Mark3Label)
                                    .addComponent(Mark3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Mark4Label)
                                    .addComponent(Mark4Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mark5Label)
                    .addComponent(Mark5Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mark2TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mark2TextActionPerformed
        
    }//GEN-LAST:event_Mark2TextActionPerformed

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        //Declaring Array "Marks"
        double [] marks = new double [5];
        //Declaring Values For Marks
        marks [0] = Double.parseDouble(Mark1Text.getText());
        marks [1] = Double.parseDouble(Mark2Text.getText());
        marks [2] = Double.parseDouble(Mark3Text.getText());
        marks [3] = Double.parseDouble(Mark4Text.getText());
        marks [4] = Double.parseDouble(Mark5Text.getText());
        
        //Variables
        double total = 0;
        double average;
        
        //Finding Total Of Marks
            for(int i = 0; i <= 4; i = i+1)
            { 
                total = total + marks[i];
            }
            
        //Finding Average
        average = total/5;
        
        //Calculations
        average = average*10;
        average = Math.round(average);
        average = average/10;
        
        //Setting Average
        AverageLabel2.setText(average+"%");
        
        //Setting DisplayLabel Text With If Statements
        if (average<=49)
        {
            DisplayLabel.setText("You failed");
        } 
        if (average>=50)
        {
            DisplayLabel.setText("Well, at least you're trying.");
        }    
        if (average>=70)
        {
            DisplayLabel.setText("You passed. That's what counts.");
        } 
        if (average>=80)
        {
            DisplayLabel.setText("You're progressing well.");
        } 
        if (average>=90)
        {
            DisplayLabel.setText("Great job!");
        } 
    }//GEN-LAST:event_CalculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCourseMarkCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCourseMarkCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCourseMarkCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCourseMarkCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCourseMarkCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AverageLabel;
    private javax.swing.JLabel AverageLabel2;
    private javax.swing.JButton CalculateButton;
    private javax.swing.JLabel DisplayLabel;
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JLabel Mark1Label;
    private javax.swing.JTextField Mark1Text;
    private javax.swing.JLabel Mark2Label;
    private javax.swing.JTextField Mark2Text;
    private javax.swing.JLabel Mark3Label;
    private javax.swing.JTextField Mark3Text;
    private javax.swing.JLabel Mark4Label;
    private javax.swing.JTextField Mark4Text;
    private javax.swing.JLabel Mark5Label;
    private javax.swing.JTextField Mark5Text;
    private javax.swing.JLabel SubheadingLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
